-- 1. 방명록 테이블 생성
create table guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- 2. 좋아요 테이블 생성
create table likes (
  id text primary key,
  count integer default 0
);
-- 3. 좋아요 초기 데이터 삽입
insert into likes (id, count)
values ('main', 154) ON CONFLICT DO NOTHING;
-- 4. 권한 설정 (누구나 읽기/쓰기 가능)
alter table guestbook enable row level security;
alter table likes enable row level security;
-- 방명록 정책 (누구나 읽기/쓰기 허용)
create policy "Enable read access for all users" on guestbook for
select using (true);
create policy "Enable insert access for all users" on guestbook for
insert with check (true);
create policy "Enable delete for everyone" on guestbook for delete using (true);
-- 좋아요 정책 (누구나 읽기/업데이트 허용)
create policy "Enable read access for all users" on likes for
select using (true);
create policy "Enable update access for all users" on likes for
update using (true);